### ISSUE TITLE
명령어 노출 텍스트 이슈

### ISSUE THREAD

**Issue by HW0810** [CelNuc/celnuc-bot#1]
>명령어 입력 시 노출되는 텍스트 접두사 변경

![66834691-B6B0-4E4D-8DF1-15292F6D9694](https://user-images.githubusercontent.com/86562665/123548937-e369cb80-d7a1-11eb-8fd6-48ff5e9dcc7f.jpeg)

**Comment by CelNuc** [comment]
해당 이슈가 임시적으로 해결되었습니다.
