### ISSUE TITLE
명령어 리스트 노출 관련 건의

### ISSUE THREAD

**Issue by HW0810** [CelNuc/celnuc-bot#11]
.명령어 입력 시 노출되는 텍스트의 행간이 좁아 가독성이 떨어져 보입니다. 행간을 따로 조절하는 기능이 없기에 종류별 구분, 순번 혹은 글머리 기호 추가로 전반적인 가독성이 높아졌으면 합니다.

![image](https://user-images.githubusercontent.com/86562665/123796140-c4914380-d91f-11eb-992d-b3906bde3f91.jpeg)

**Comment by CelNuc** [comment]
이 문제는 새로운 베타버전에서 해결될 예정입니다.
