### ISSUE TITLE
관리자 권한 관련

### ISSUE THREAD

**Issue by REPO4862** [CelNuc/celnuc-bot#12]
관리자 권한이 없는 유저가 권한이 필요한 명령어를 사용할 경우 발생하는 택스트 오류
![Screenshot_20210630-095612_Discord-Beta](https://user-images.githubusercontent.com/86563015/123886077-a102e300-d989-11eb-8536-9bf8bc111e56.jpg)

**Comment by CelNuc** [comment]
제보 감사합니다. 이 버그는 수정되었습니다.
