### ISSUE TITLE
엉클봇 업적 신청1

### ISSUE THREAD

**Issue by REPO4862** [CelNuc/celnuc-bot#13]
엉클봇 레벨을 0부터 시작하고 택스트 1개만 입력해서 1레벨로 올라가고 1레벨이 되면 **엉클봇의 시작** 그런 업적 만들어 주세요.

레벨 10되면 **엉클봇의 고수** 그런거 만들어 주세요.

돈을 1원 모으면 **자본주의의 시작** 그런거 만들어 주세요

처음으로 송금하면 **나눔의 기쁨** 뭐 그런거 만들어 주세요.

처음으로 배지 얻으면 뭐 대충 배지 어쩌구 그런 업적 만들어 주세요.

처음으로 놀이기능을 하면 뭐 놀이 뭐시기 추가 해줘요.

뭐 대충 처음으로 경고먹으면 뭐 추가 해줘요.

**Comment by HW0810** [comment]
[간략 정리]

1. 텍스트 1개 입력 후 1레벨 달성 시, **엉클봇의 시작** 업적 달성
2. 10레벨 달성 시, **엉클봇의 고수** 업적 달성
3. 돈 누적 1원 달성 시, **자본주의의 시작** 업적 달성
4. 첫 송금 시, **나눔의 기쁨** 업적 달성

5. 첫 뱃지 획득 시, **대충 배지 어짜구..** 업적 달성
6. 놀이기능 첫 사용 시, **놀이 어쩌구..** 업적 달성
7.  첫 경고 누적 시, **경고 어쩌구..** 업적 달성
ㄴ 5~7번 업적명은 미정

**Comment by CelNuc** [comment]
제안 감사합니다. 내부 검토 후에 기능 추가 여부가 결정될 예정입니다.
