### ISSUE TITLE
엉클봇 레벨 혜택

### ISSUE THREAD

**Issue by Taegi88** [CelNuc/celnuc-bot#14]
엉클봇 레벨마다 특별한 혜택이나 변화를 주는건 어떨까요
이름 컬러가 바뀐다거나 미니게임을 할 때 보상이 약간 더 좋아진다던가 그런거요

**Comment by CelNuc** [comment]
제안 감사합니다. 내부 검토 후에 정식 반영 여부를 결정할 예정입니다.
