### ISSUE TITLE
상점에서 팔거

### ISSUE THREAD

**Issue by REPO4862** [CelNuc/celnuc-bot#16]
대충 이름설정 아이탬**(울트라짱짱 비쌈)**
 
별 쿨타임 3시간 감소(일회용)(하루당 1개)

경험치 2배 쿠폰(일회용)

대충 개인 서버별 역할 판매 
ex:>상점역할 [역할] [가격{1원 이상부터}]

미니게임 해금

배지 신청권(짱짱 비쌈)

**Comment by CelNuc** [comment]
제안 감사합니다. 

STAR 기능은 엉클봇에서 가장 신뢰도가 요구되는 기능으로 유료 구독 여부, 시스템 내 계급에 따라 쿨타임 또는 개수를 차등 설정하지 않고 있습니다. 따라서 STAR 관련한 제안은 반영되기 어렵다는 점 참고 바랍니다.

나머지 기능들에 대해선 내부 검토 후에 기능 추가 여부가 결정될 예정입니다. 감사합니다.
