### ISSUE TITLE
별 전송, 일일보상 관련 버그

### ISSUE THREAD

**Issue by tkxkd444** [CelNuc/celnuc-bot#21]
별 전송이나 일일보상 명령어를 사용했을 때, 명령어가 실행은 되지 않고 아래와 같이 **`-시간 전`에 다시 확인하세요** 
라고 뜨는 버그 

![image](https://user-images.githubusercontent.com/83091722/125997915-dd275b98-3ca4-4992-b06e-f0829eef259e.png)

**Comment by REPO4862** [comment]
>

**Comment by CelNuc** [comment]
버그 제보 감사합니다. 해당 이슈는 해결되었습니다.
