### ISSUE TITLE
송금시 상대방에게 메모 표시

### ISSUE THREAD

**Issue by Camt4372** [CelNuc/celnuc-bot#22]
송금하고 상대방한테 메모와 함께 돈을 주게 해주세용

ex) >송금 @Camt4372 100 선물이얌!

송금완료!

받는사람
Camt4372

보낸금액
100원

수수료
100원

보낸이 메모
선물이얌!

labels:제안

**Comment by CelNuc** [comment]
이 기능은 새로운 베타 버전에서 추가될 예정입니다.
