### ISSUE TITLE
스틸ㅋㅋㅋㅋㅋㅋㅋㅋ

### ISSUE THREAD

**Issue by REPO4862** [CelNuc/celnuc-bot#5]
돈을 빼앗는 음수 송금 버그 수정요청 ![Screenshot_20210628-012101_Discord-Beta.jpg](https://user-images.githubusercontent.com/86563015/123552017-3dbd5900-d7af-11eb-8806-0596cb939a9f.jpg)

**Comment by CelNuc** [comment]
해당 문제는 엉클봇 Beta 1.0 업데이트에서 해결되었습니다.
