### ISSUE TITLE
아조씨 여기 버그 났어요

### ISSUE THREAD

**Issue by REPO4862** [CelNuc/celnuc-bot#6]
잘은 모르겠지만 음수 송금버그를 인피니티가 뜨게 쓰는 바람에 그 버그로는 돈이 추가가 안되는데 돈의 변동자체의 문제가 생긴건지 송금의 의한 변동에 문제가 생긴건진 모르겠지만 암튼 더블 버그입니돠

**Comment by CelNuc** [comment]
해당 문제는 엉클봇 Beta 1.0 업데이트를 진행하면서 은행 DB를 초기화하며 해결되었습니다.
