### ISSUE TITLE
택스트

### ISSUE THREAD

**Issue by REPO4862** [CelNuc/celnuc-bot#8]
![Screenshot_20210629-172441_Discord-Beta.jpg](https://user-images.githubusercontent.com/86563015/123763620-f1812e80-d8fe-11eb-8549-5ba5a33ed208.jpg)
해당 택스트를 바꿔 주실 수 있으신가요?

**Comment by CelNuc** [comment]
핫픽스 1.1 업데이트로 패치되었습니다.
