### ISSUE TITLE
접두사 관련

### ISSUE THREAD

**Issue by REPO4862** [CelNuc/celnuc-bot#9]
![Screenshot_20210629-172805_Discord-Beta.jpg](https://user-images.githubusercontent.com/86563015/123764116-72d8c100-d8ff-11eb-8c36-0220c4f077f8.jpg)
엉클봇과 엉클봇 알파의 접두사가 겹쳤네요 아이고

**Comment by CelNuc** [comment]
해당 이슈는 Beta 1.1 HotFix 패치로 해결되었습니다.
